spring:
  kafka:
    consumer:
      group-id: groupId
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual

  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: username
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 80
logging:
  level:
    com.github.josh910830: debug