version: '3'

services:

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
